### ISSUE TITLE
Page is getting reloaded on click of menu Item.

### ISSUE THREAD

**Issue by kishoreaoe** [sudhaparayil/Angular-Material-angular6#1]
Hi @sudhaparayil ,

thanks for the work done. One small issue which i have faced is- "on click of a menu item, the page is getting refreshed/reloaded. Actually the page should not get reloaded and only VIEW should be loaded.

Could you please suggest on this issue.

Thanks,
K K

**Comment by kishoreaoe** [comment]
@sudhaparayil , Understood the problem. Actually its just redirecting with href. Please close this issue.

**Comment by sudhaparayil** [comment]
Hi,
update your -Angular-Material-angular6/src/app/components/dashboard/dashboard.component.html

`<mat-nav-list>
      <a mat-list-item routerLink="/first-page">First Page</a>
      <a mat-list-item routerLink="/data-table">Second Page</a>
      <a mat-list-item routerLink="/data-dashboard">Third Page</a>
    </mat-nav-list>`
